### ISSUE TITLE
Classify cats and dogs

### ISSUE THREAD

**Issue by VitaliiKinakh** [SeYearSt/Neural_Networks#1]
I am trying to use your neural network to classify cats and dogs. But it doesn't work. 
Please, help me

**Comment by SeYearSt** [comment]
Let see, give please full code, so we could investigate problem.

**Comment by VitaliiKinakh** [comment]
Sure. Here it is

`% init model
net = newp([-9 9; -9 9], 3);
net.IW{1} = [-0.1 0; -0.5 0.3; 1 1];
net.b{1} = [-0.2; 0.5; 0.1];

% test model
input_data = [-0.2 -0.2; -0.1 -0.1; 0 0; 0.1 0.1; 0.2 0.2];
s = size(input_data);
n = s(1);
for i=1:n
    %input_data(i, :)
    sim(net, input_data(i, :)')
end
`

**Comment by SeYearSt** [comment]
Okey. First of all, I can't see code that responsible for loading data. I mean if you want to differentiate cats and dogs you really should have pictures of cats and dogs. You can use this code if you have some features of cats and docks. I would recommend a [fast.ai](https://www.fast.ai/) course and especially a [lesson1](https://course.fast.ai/videos/?lesson=1) that will help you to manage to overcome this problem. I close this issue due to the question is not related to this repository.
